version: '3.8'
services:
  
  devcontainer:
    container_name: info-5940-devcontainer
    build:
      dockerfile: Dockerfile
      target: devcontainer
    environment:
      - OPENAI_API_KEY = [input_open_ai_key]
      - OPENAI_BASE_URL = https://api.ai.it.cornell.edu/
      - TZ = America/New_York
    volumes:
      - '$HOME/.aws:/root/.aws'
      - '.:/workspace'
    env_file:
      - .env